### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by janus** [wearekickback/contracts#44]
Just downloaded and followed the steps.
What could cause test to fail? 

From ganache-cli

  Transaction: 0x1f625d8fd078caac43c816ba1cc635c1bcc3a0c747b7ca7a7e5c9dd608e85018
  Contract created: 0x201e119207151e6d15fd89e9a77f472526e4b819
  Gas usage: 6721975
  Block Number: 4
  Block Time: Wed Dec 04 2019 11:26:29 GMT+0100 (West Africa Standard Time)
  Runtime Error: invalid opcode

 Contract: ETH Conference
    on registration

      1) tokenAddress is empty
    > No events were emitted
      on changeName

        2) "before each" hook for "owner can rename the event"
      on changeDeposit

        3) "before each" hook for "owner can change the deposit"
      on setLimitOfParticipants

        4) "before each" hook for "does not allow to register more than the limit"
      on creation
        ✓ name cannot be empty
        ✓ deposit cannot be empty
        ✓ limitOfParticipants cannot be empty
        ✓ coolingPeriod cannot be empty
        ✓ ownerAddress cannot be empty
        ✓ cannot set empty address as an owner (6721975 gas)

        5) can set config values
    > No events were emitted
      on registration

        6) "before each" hook for "increments registered"
      on failed registration

        7) "before each" hook for "cannot be registered if wrong amount of deposit is sent"
      finalize using attendee bitmap

        8) "before each" hook for "can be called by owner"
      empty events

        9) "before each" hook for "nothing to withdraw if no one registered"
      on cancel

        10) "before each" hook for "cannot cancel if non owner calls"
      on withdraw

        11) "before each" hook for "cannot withdraw twice"
      on clear

        12) "before each" hook for "cooling period can be set"

  Contract: Deployer

    13) "before each" hook for "does not accept ETH"

  Contract: ERC20 Conference
    on changeName

      14) "before each" hook for "owner can rename the event"

  Contract: NPM exports
    ✓ exports contracts
    ✓ exports valid events

  Contract: GroupAdmin
    on new

      15) "before each" hook for "owner is admin"

  Contract: ETH Conference - stress tests
    on big party
      finalize large party using attendee bitmaps

        16) requires valid input to succeed
    > No events were emitted
        success modes

          17) "before each" hook for "correctly updates attendee records - p1, p2, p256, p257, p298, p299"

·-----------------------------------------------|----------------------------·
|                      Gas                      ·  Block limit: 6721975 gas  │
························|·······················|·····························
|  Methods              ·      1 gwei/gas       ·       146.47 usd/eth       │
·············|··········|·······|·······|·······|·············|···············
|  Contract  ·  Method  ·  Min  ·  Max  ·  Avg  ·  # calls    ·  usd (avg)   │
·------------|----------|-------|-------|-------|-------------|--------------·

  8 passing (30s)
  17 failing

  1) Contract: ETH Conference
       on registration
         tokenAddress is empty:
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at Context.createConference (test/conference.js:43:36)
      at Context._callee4$ (test/conference.js:120:27)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/conference.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/conference.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/conference.js:3:99)

  2) Contract: ETH Conference
       on registration
         on changeName
           "before each" hook for "owner can rename the event":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee2$ (test/behaviors/conference.behavior.js:74:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  3) Contract: ETH Conference
       on registration
         on changeDeposit
           "before each" hook for "owner can change the deposit":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee6$ (test/behaviors/conference.behavior.js:168:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  4) Contract: ETH Conference
       on registration
         on setLimitOfParticipants
           "before each" hook for "does not allow to register more than the limit":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee10$ (test/behaviors/conference.behavior.js:263:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  5) Contract: ETH Conference
       on registration
         on creation
           can set config values:
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee15$ (test/behaviors/conference.behavior.js:403:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  6) Contract: ETH Conference
       on registration
         on registration
           "before each" hook for "increments registered":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee16$ (test/behaviors/conference.behavior.js:453:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  7) Contract: ETH Conference
       on registration
         on failed registration
           "before each" hook for "cannot be registered if wrong amount of deposit is sent":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee21$ (test/behaviors/conference.behavior.js:577:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  8) Contract: ETH Conference
       on registration
         finalize using attendee bitmap
           "before each" hook for "can be called by owner":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee24$ (test/behaviors/conference.behavior.js:679:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  9) Contract: ETH Conference
       on registration
         empty events
           "before each" hook for "nothing to withdraw if no one registered":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee36$ (test/behaviors/conference.behavior.js:1047:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  10) Contract: ETH Conference
       on registration
         on cancel
           "before each" hook for "cannot cancel if non owner calls":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee39$ (test/behaviors/conference.behavior.js:1146:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  11) Contract: ETH Conference
       on registration
         on withdraw
           "before each" hook for "cannot withdraw twice":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee44$ (test/behaviors/conference.behavior.js:1393:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  12) Contract: ETH Conference
       on registration
         on clear
           "before each" hook for "cooling period can be set":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/conference.js:43:36)
      at Context._callee48$ (test/behaviors/conference.behavior.js:1531:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conference.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conference.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conference.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  13) Contract: Deployer
       "before each" hook for "does not accept ETH":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at _callee$ (test/deployer.js:38:32)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/deployer.js:9:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/deployer.js:9:361
      at processTicksAndRejections (internal/process/task_queues.js:86:5)

  14) Contract: ERC20 Conference
       "before each" hook for "owner can rename the event":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at Context._callee3$ (test/erc20_conference.js:28:29)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/erc20_conference.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/erc20_conference.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/erc20_conference.js:3:99)
      at web3.eth.getBlockNumber.then.result (node_modules/truffle/build/webpack:/packages/core/lib/testing/testrunner.js:161:1)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)

  15) Contract: GroupAdmin
       "before each" hook for "owner is admin":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at Context._callee$ (test/group_admin.js:25:46)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/group_admin.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/group_admin.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/group_admin.js:3:99)
      at web3.eth.getBlockNumber.then.result (node_modules/truffle/build/webpack:/packages/core/lib/testing/testrunner.js:161:1)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)

  16) Contract: ETH Conference - stress tests
       on big party
         finalize large party using attendee bitmaps
           requires valid input to succeed:
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/stress.js:42:36)
      at Context._callee2$ (test/behaviors/conferenceFinalize.behavior.js:65:34)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conferenceFinalize.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conferenceFinalize.behavior.js:3:437
      at new Promise (<anonymous>)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conferenceFinalize.behavior.js:3:99
      at createConferenceAndRegisterParticipants (test/behaviors/conferenceFinalize.behavior.js:102:32)
      at Suite._callee4$ (test/behaviors/conferenceFinalize.behavior.js:120:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conferenceFinalize.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conferenceFinalize.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conferenceFinalize.behavior.js:3:99)

  17) Contract: ETH Conference - stress tests
       on big party
         finalize large party using attendee bitmaps
           success modes
             "before each" hook for "correctly updates attendee records - p1, p2, p256, p257, p298, p299":
     Error: Returned error: VM Exception while processing transaction: invalid opcode
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at createConference (test/stress.js:42:36)
      at Context._callee2$ (test/behaviors/conferenceFinalize.behavior.js:65:34)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conferenceFinalize.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conferenceFinalize.behavior.js:3:437
      at new Promise (<anonymous>)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conferenceFinalize.behavior.js:3:99
      at createConferenceAndRegisterParticipants (test/behaviors/conferenceFinalize.behavior.js:102:32)
      at Suite._callee5$ (test/behaviors/conferenceFinalize.behavior.js:149:24)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/behaviors/conferenceFinalize.behavior.js:3:191)
      at /home/eka/buildtool/job/amhello/gitcoin/contracts/test/behaviors/conferenceFinalize.behavior.js:3:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test/behaviors/conferenceFinalize.behavior.js:3:99)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

error Command failed with exit code 17.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 17.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by makoto** [comment]
Did you change anything? Can you create PR with title [WIP] so that I can at least see the error message on CI.

**Comment by janus** [comment]
I could only push ... it is same as master so PR is not working.
https://github.com/janus/contracts/tree/sendAndwithdraw

**Comment by janus** [comment]
Issue resolved:
Had : Ganache CLI v6.1.8 (ganache-core: 2.2.1)
Upgraded to : Ganache CLI v6.7.0 (ganache-core: 2.8.0)

Please point out the need to have the right Ganache CLI version in the document.

**Comment by makoto** [comment]
Addressed at https://github.com/wearekickback/contracts/pull/51
